"""Display boundary between the runtime and the Textual interface."""

from __future__ import annotations

from typing import Protocol


class TranscriptPresentation(Protocol):
    """Render transcript and Codex stream events without owning runtime logic."""

    def update(self, speaker: str, text: str) -> None: ...

    def commit(self, speaker: str, text: str) -> None: ...

    def finish_turn(self, speaker: str) -> None: ...

    def close_speaker(self, speaker: str) -> None: ...

    def begin_codex(self) -> None: ...

    def codex_message_open(self, reply_to: str) -> None: ...

    def codex_delta(self, delta: str) -> None: ...

    def codex_message_close(self) -> None: ...

    def command_started(self, command: str) -> None: ...

    def command_output(self, delta: str) -> None: ...

    def command_completed(self, exit_code: int | None) -> None: ...

    def tool_called(self, server: str, tool: str) -> None: ...

    def tool_completed(self, status: str) -> None: ...

    def token_usage(self, total_tokens: int) -> None: ...

    def error(self, message: str) -> None: ...

    def note(self, text: str) -> None: ...

    def set_codex(self, **fields: object) -> None: ...

    def set_codex_catalog(
        self,
        models: list[tuple[str, str]],
        efforts_by_model: dict[str, list[str]],
        default_effort_by_model: dict[str, str],
    ) -> None: ...

    def end_codex(self) -> None: ...
